package:
  name: pyibex
  version: "1.6.2"

source:
  git_rev: master
  git_url: https://github.com/benEnsta/pyIbex

build:
  script_env:
    - CC
    - CXX
  number: 1

requirements:
  build:
    - python
    - ibex-lib >=2.4.2
    - cmake >=2.8.12
    - gcc >=4.8.5 [osx]

  run:
    - python
    - gcc >=4.8.5 [osx]
    - vs2015_runtime  [win]
    - numpy


test:
  # Python imports
  imports:
    - pyibex


  commands:
    - python -m unittest discover -vv pyibex.tests
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/benEnsta/pyIbex
  license: GNU Lesser General Public License v3 or later (LGPLv3+)
  license_file: LICENSE
  summary: 'PyIbex a python interface of ibexlib '

extra:
  recipe-maintainers:
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - BenEnsta <ben.ensta@gmail.com>
# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
