package:
  name: pyibex
  version: "1.5.0a10"

source:
  git_rev: pre_v1.5
  git_url: https://github.com/benEnsta/pyIbex

build:
#  script_env:
#    - CC
#    - CXX
  number: 9 [not osx]
  number: 1 [osx]
  features:
    - vc14    [win]
# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyibex = pyibex:main
    #
    # Would create an entry point called pyibex that calls pyibex.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    # - setuptools >=23.0.0
    - ibex-lib >=2.3.0
    - cmake >=2.8.12
    - gcc >=4.8.5 [osx]

  run:
    - python
    - gcc >=4.8.5 [osx]


test:
  # Python imports
  imports:
    - pyibex
  #   - pyibex.examples
  #   - pyibex.geometry
  #   - pyibex.polar

  commands:
    - conda list
    - echo $(pwd)
    - python -m unittest discover -v pyibex.tests
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/benEnsta/pyIbex
  license: GNU Lesser General Public License v3 or later (LGPLv3+)
  license_file: LICENSE
  summary: 'PyIbex a python interface of ibexlib '

extra:
  recipe-maintainers:
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - BenEnsta
# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
