#!/usr/bin/env bash

set -e


wget https://raw.githubusercontent.com/pelson/Obvious-CI/master/bootstrap-obvious-ci-and-miniconda.py
python bootstrap-obvious-ci-and-miniconda.py ~/miniconda x64 3 --without-obvci && source ~/miniconda/bin/activate root
conda config --set show_channel_urls true
conda config --add channels conda-forge
conda config --add channels benensta;
conda install --yes --quiet conda-build
conda install --yes --quiet anaconda-client
conda install --yes --quiet conda-build-all

rm -rf ./recipes/example

conda-build-all ./recipes --matrix-condition "numpy >=1.10" "python >=2.7,<3|>=3.4" --inspect-channels benensta --upload-channels benensta
